default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "") %>
  username: <%= ENV.fetch("DB_USERNAME", "") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  <<: *default
  database: policy_management_dev

test:
  <<: *default
  database: policy_management_test

production:
  primary:
    <<: *default
    database: policy_management_prod
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *default
    database: policy_management_queue
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: policy_management_cache
    migrations_paths: db/cache_migrate
